// <auto-generated>
// GENERATED by tools/generate_hud.py - edit the generator, not this file. It writes the Panorama
// layout and stylesheet from the same spec, so every id and class below exists in the layout.
// </auto-generated>

namespace CSRoll.Hud;

public static partial class HudLayout
{
    public const string HudPanel = "csr_hud";
    public const string PromptPanel = "csr_prompt";
    public const string ListPanel = "csr_list";
    public const string ListTitle = "csr_list_title";
    public const string RollPanel = "csr_roll";
    public const string Strip = "csr_strip";
    public const string Card = "csr_card";
    public const string CardIcon = "csr_card_ico";
    public const string CardCategory = "csr_card_cat";
    public const string CardName = "csr_card_name";
    public const string CardDescription = "csr_card_desc";

    public const int Rows = 6;
    public const int Gauges = 3;
    public const int FillSteps = 100;
    public const int ListOffsets = 5;

    public const int Tiles = 30;
    public const int StartTile = 3;
    public const int WinTile = 26;
    public const float SpinSeconds = 4.0f;
    public const int PositionQuantum = 4;
    public const int PositionSteps = 437;
    public static readonly (float X1, float Y1, float X2, float Y2) SpinCurve = (0.08f, 0.7f, 0.12f, 1.0f);

    public const string FallbackIcon = "InfiniteRoll";

    public static readonly string[] Icons =
    [
        "AtomicExplosions",
        "BoomerangBullets",
        "Bounty",
        "BunnyHop",
        "Butterfingers",
        "ButterflyEffect",
        "ChineseGrenades",
        "ClusterGrenades",
        "ConditionalInvisibility",
        "DisarmingBullets",
        "Drunk",
        "Flanker",
        "FlashingBullets",
        "HardHead",
        "HeavyBoots",
        "IncreasedSpread",
        "InfiniteAmmo",
        "InfiniteRoll",
        "Jetpack",
        "Juggernaut",
        "LongerFlashes",
        "MasterZeus",
        "Mimic",
        "MoreDamage",
        "NoRecoil",
        "OnePerReload",
        "PlantAnywhere",
        "PoisonousSmoke",
        "RandomHealth",
        "RandomLoadout",
        "Recall",
        "Regeneration",
        "Revive",
        "Saint",
        "SmallPlayers",
        "SmokeImmunity",
        "Speedhack",
        "SteelBody",
        "SuicideBomber",
        "SwapOnDeath",
        "SwapOnHit",
        "TeleportOnHit",
        "TeleportOnReload",
        "Vampire",
        "Vanish",
        "WalkingGrenadier",
        "Wallhack",
        "WeaponRoulette",
    ];

    public static readonly string[] Categories = ["move", "weap", "util", "surv", "stealth", "chaos"];

    public static string Row(int i) => $"csr_row{i}";
    public static string RowIcon(int i) => $"csr_row{i}_ico";
    public static string RowName(int i) => $"csr_row{i}_name";
    public static string RowShort(int i) => $"csr_row{i}_short";
    public static string Gauge(int i) => $"csr_g{i}";
    public static string GaugeIcon(int i) => $"csr_g{i}_ico";
    public static string GaugeLabel(int i) => $"csr_g{i}_label";
    public static string GaugeValue(int i) => $"csr_g{i}_val";
    public static string GaugeFill(int i) => $"csr_g{i}_fill";
    public static string Tile(int i) => $"csr_t{i}";
    public static string TileIcon(int i) => $"csr_t{i}_ico";

    public static string IconClass(string icon) => $"ico-{icon}";
    public static string CategoryClass(string category) => $"cat-{category}";
    public static string FillClass(int step) => $"f{step}";
    public static string PositionClass(int step) => $"p{step}";
    public static string ListOffsetClass(int offset) => $"y{offset}";

    /// <summary>Text variable names, as written in the layout's {s:...} slots.</summary>
    public const string VarTitle = "title";
    public const string VarName = "name";
    public const string VarShort = "short";
    public const string VarLabel = "label";
    public const string VarValue = "val";
    public const string VarCategory = "cat";
    public const string VarDescription = "desc";

    public const string On = "on";
    public const string Ready = "ready";
    public const string Won = "won";
}
