using SwiftlyS2.Shared.GameEventDefinitions;
using SwiftlyS2.Shared.Misc;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Shared.SchemaDefinitions;

using CSRoll.Core;

namespace CSRoll.Modifiers;

/// <summary>
/// 1 bullet per magazine - the assigned player's weapon is kept at exactly 1 round in the clip,
/// reserve ammo kept topped up so reloading never actually runs dry.
///
/// Bug fix: this used to shrink CBasePlayerWeaponVData.MaxClip1, a field shared by the weapon TYPE
/// across every player holding one (not a per-instance field) - and did so unconditionally in
/// OnEnabled/OnDisabled/OnItemEquip/OnWeaponReload with no IsAssignedTo check anywhere at all, so
/// activating this modifier for one player capped EVERY connected player's matching weapons to 1
/// bullet, and would have silently ignored !memodifier's "just you" scoping entirely too.
///
/// Bug fix 2: the next rewrite force-set Clip1=1 and topped up reserve ammo, both directly inside the
/// OnWeaponReload event handler - but that turned out to depend on exactly when that event fires
/// relative to the engine's own native ammo transfer, and got it wrong in two different directions on
/// two different attempts (first: reload gave back a full magazine, because the transfer ran AFTER
/// the event and drew from the reserve we'd just topped up; second attempt at fixing that moved
/// Clip1 to a per-tick clamp but left the reserve top-up event-driven, which could still leave
/// reserve at 0 - "can't reload anymore" - if the transfer instead ran BEFORE the event, or under
/// some other ordering this hadn't accounted for). Rather than guess a third time at the exact event
/// ordering, both Clip1 and reserve are now enforced unconditionally every tick, independent of the
/// reload event entirely: Clip1 is clamped down to at most 1, and reserve is topped back up to max
/// whenever it's below max. Neither can drift away from "exactly 1 in the clip, full reserve always"
/// for more than a tick, regardless of what order the native reload logic does its own ammo math in.
/// </summary>
public sealed class GameModifierOnePerMag : GameModifierBase
{
    public GameModifierOnePerMag()
    {
        Name = "OnePerReload";
        Description = "1 bullet per reload";
        SupportsRandomRounds = true;
        SupportsPerPlayerRandomization = true;
        IncompatibleModifiers = ["InfiniteAmmo"];
    }

    protected override void OnEnabled()
    {
        Core.Event.OnTick += EnforceOnePerMag;
    }

    protected override void OnDisabled()
    {
        Core.Event.OnTick -= EnforceOnePerMag;
    }

    private void EnforceOnePerMag()
    {
        foreach (var player in GetAssignedPlayers())
        {
            if (player.PlayerPawn?.WeaponServices?.ActiveWeapon.Value is not { IsValid: true } weapon)
            {
                continue;
            }

            if (weapon.Clip1 > 1)
            {
                weapon.Clip1 = 1;
                weapon.Clip1Updated();
            }

            if (weapon.PlayerWeaponVData?.As<CCSWeaponBaseVData>() is { } vData && weapon.ReserveAmmo[0] < vData.PrimaryReserveAmmoMax)
            {
                weapon.ReserveAmmo[0] = vData.PrimaryReserveAmmoMax;
                weapon.ReserveAmmoUpdated();
            }
        }
    }
}

/// <summary>
/// No recoil and no spread for whoever rolled it, for whatever weapon they're holding.
///
/// Bug fix: this used to also have a bolt-on ModifierConfig/NoSpread.cfg setting the server-wide
/// weapon_accuracy_nospread cvar to true - completely redundant with (and worse than) the per-player
/// aim-punch cancellation below, since it silently gave every connected player perfect accuracy the
/// instant this modifier activated for anyone, not just the assigned player. Deleted.
///
/// Renamed from NoSpread to NoRecoil, and from then on it only ever cancelled aim punch (zeroing
/// CCSPlayer_AimPunchServices every tick) - bullet spread was untouched, reported as "should remove the
/// recoil AND spread". Spread can't be removed per weapon instance: the spread/inaccuracy values live
/// in CCSWeaponBaseVData, which every weapon of that type shares across all players. So both halves
/// now go through Runtime.ConVarOverrides, which switches the real weapon convars only while the server
/// simulates THIS player (their shots included) and replicates the same values to their client:
///   weapon_accuracy_nospread 1        - no spread or inaccuracy, on the server's own hit traces
///   weapon_recoil_scale 0             - no aim punch is generated by firing at all
///   weapon_recoil_view_punch_extra 0  - no camera kick on top of it
/// The client predicts the same thing it's told, so tracers, decals and the crosshair agree with where
/// the server actually lands the shots. Shotgun pellets all land on the crosshair as a result - that is
/// what no spread means for a shotgun.
///
/// The per-tick aim punch zeroing is kept as a fallback in case a CS2 build fires weapons outside the
/// code ConVarOverrides wraps; it now only writes when something is non-zero, so it costs nothing
/// (and no network updates) while the convars are doing their job. AccuracyPenalty (the per-instance
/// spray/movement bloom) gets the same treatment for the same reason.
/// </summary>
public sealed class GameModifierNoRecoil : GameModifierBase
{
    private static readonly IReadOnlyList<(string Name, string Value)> NoRecoilConVars =
    [
        ("weapon_accuracy_nospread", "1"),
        ("weapon_recoil_scale", "0"),
        ("weapon_recoil_view_punch_extra", "0"),
    ];

    private Guid _spawnHookId;

    public GameModifierNoRecoil()
    {
        Name = "NoRecoil";
        Description = "Weapons have no recoil and no spread";
        SupportsRandomRounds = true;
        SupportsPerPlayerRandomization = true;
    }

    protected override void OnEnabled()
    {
        Core.Event.OnTick += CancelAimPunch;
        _spawnHookId = Core.GameEvent.HookPost<EventPlayerSpawn>(OnPlayerSpawn);

        foreach (var player in GetAssignedPlayers())
        {
            Runtime.ConVarOverrides.Set(this, player.Slot, NoRecoilConVars);
        }
    }

    protected override void OnDisabled()
    {
        Core.Event.OnTick -= CancelAimPunch;
        Core.GameEvent.Unhook(_spawnHookId);

        Runtime.ConVarOverrides.RemoveAll(this);
    }

    /// <summary>Handed NoRecoil mid-round (ButterflyEffect, Mimic) - OnEnabled doesn't re-run for these.</summary>
    protected override void OnSlotsAdded(IReadOnlyCollection<int> slots)
    {
        foreach (var slot in slots)
        {
            Runtime.ConVarOverrides.Set(this, slot, NoRecoilConVars);
        }
    }

    protected override void OnSlotsRemoved(IReadOnlyCollection<int> slots)
    {
        foreach (var slot in slots)
        {
            Runtime.ConVarOverrides.Remove(this, slot);
        }
    }

    /// <summary>A player joining mid-round while this is active globally (!rolltoggle) is in scope but was never handed the overrides.</summary>
    private HookResult OnPlayerSpawn(EventPlayerSpawn @event)
    {
        if (@event.UserIdPlayer is { IsValid: true } player && IsAssignedTo(player.Slot))
        {
            Runtime.ConVarOverrides.Set(this, player.Slot, NoRecoilConVars);
        }

        return HookResult.Continue;
    }

    private void CancelAimPunch()
    {
        foreach (var player in Core.PlayerManager.GetAlive())
        {
            if (!IsAssignedTo(player.Slot) || player.PlayerPawn is not { IsValid: true } pawn)
            {
                continue;
            }

            if (pawn.AimPunchServices is { IsValid: true } aimPunch)
            {
                if (!IsZero(aimPunch.PredictableBaseAngle))
                {
                    aimPunch.PredictableBaseAngle = default;
                    aimPunch.PredictableBaseAngleUpdated();
                }

                if (!IsZero(aimPunch.PredictableBaseAngleVel))
                {
                    aimPunch.PredictableBaseAngleVel = default;
                    aimPunch.PredictableBaseAngleVelUpdated();
                }

                if (aimPunch.PredictableBaseTickInterpAmount != 0f)
                {
                    aimPunch.PredictableBaseTickInterpAmount = 0f;
                    aimPunch.PredictableBaseTickInterpAmountUpdated();
                }

                if (!IsZero(aimPunch.UnpredictableBaseAngle))
                {
                    aimPunch.UnpredictableBaseAngle = default;
                    aimPunch.UnpredictableBaseAngleUpdated();
                }
            }

            if (pawn.WeaponServices?.ActiveWeapon.Value is { IsValid: true } weapon)
            {
                var csWeapon = weapon.As<CCSWeaponBase>();
                if (csWeapon.AccuracyPenalty != 0f)
                {
                    csWeapon.AccuracyPenalty = 0f;
                    csWeapon.AccuracyPenaltyUpdated();
                }
            }
        }
    }

    private static bool IsZero(QAngle angle) => angle.Pitch == 0f && angle.Yaw == 0f && angle.Roll == 0f;
}
