#!/usr/bin/env python3
"""
Generates the CSRoll custom HUD from one spec, so the three halves can never disagree:

    hud/panorama/layout/custom_game/csroll_hud.xml     the Panorama layout
    hud/panorama/styles/custom_game/csroll_hud.css     its stylesheet
    src/Hud/HudLayout.g.cs                             the ids, classes and timings the plugin drives

    python3 tools/generate_hud.py

Edit this file, never the outputs. A panel id or class the plugin writes that the layout lacks fails
silently in game - the write is simply dropped - so the only safe contract is one written once.

Panorama is not the web (see the cs2-panorama-hud skill): no flexbox, no calc(), #rrggbbaa colours
only, gradients in the 2008 WebKit form, keyframe names QUOTED with the brace on the same line and
declared above their first use - an unparsable keyframe throws the whole stylesheet away.
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICON_DIR = ROOT / "hud/panorama/images/custom_game/csroll"
LAYOUT = ROOT / "hud/panorama/layout/custom_game/csroll_hud.xml"
STYLE = ROOT / "hud/panorama/styles/custom_game/csroll_hud.css"
CONTRACT = ROOT / "src/Hud/HudLayout.g.cs"

# ---------------------------------------------------------------------------------------------------
# Spec
# ---------------------------------------------------------------------------------------------------
ROWS = 6            # active-modifier rows in the left list
GAUGES = 3          # floating gauges above the bottom HUD
FILL_STEPS = 20     # bar resolution: 5% per step, driven by clip (width resets when text updates)
LIST_OFFSETS = [360, 400, 440, 480, 520]   # list top margins (px @1080p) - radar scale varies per player

TILES = 30          # carousel tiles
START_TILE = 3      # tile under the marker when the spin starts
WIN_TILE = 26       # tile the spin lands on - the only per-player tile
TILE = 64           # px
TILE_GAP = 10       # px
REEL_WIDTH = 600    # px
SPIN_SECONDS = 4.0
# Ease-out the server also evaluates to time each tick sound to a tile crossing the marker.
BEZIER = (0.08, 0.70, 0.12, 1.00)

FALLBACK_ICON = "InfiniteRoll"

# Category -> accent. Six classes tint every icon, row edge, tile edge and bar.
CATEGORIES = {
    "move":    "#4fd1c5",
    "weap":    "#f6ad55",
    "util":    "#a3e635",
    "surv":    "#f56565",
    "stealth": "#b794f4",
    "chaos":   "#ed64a6",
}

STEP = TILE + TILE_GAP
STRIP_WIDTH = TILES * STEP
STRIP_LEFT = REEL_WIDTH // 2 - (START_TILE * STEP + TILE // 2)
TRAVEL = (WIN_TILE - START_TILE) * STEP

FONT_BOLD = "Stratum2 Bold"
FONT_MEDIUM = "Stratum2 Medium Condensed"
FONT_BODY = "Stratum2"
SHADE = "#0a0d11"


def icons() -> list[str]:
    names = sorted(p.stem for p in ICON_DIR.glob("*.svg"))
    if FALLBACK_ICON not in names:
        sys.exit(f"missing fallback icon {FALLBACK_ICON}.svg in {ICON_DIR}")
    return names


# ---------------------------------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------------------------------
def layout() -> str:
    rows = "\n".join(
        f'''        <Panel id="csr_row{i}" class="CsrRow">
          <Panel id="csr_row{i}_ico" class="CsrIco CsrRowIco" />
          <Panel class="CsrRowText">
            <Label id="csr_row{i}_name" class="CsrRowName" text="{{s:name}}" />
            <Label id="csr_row{i}_short" class="CsrRowShort" text="{{s:short}}" />
          </Panel>
        </Panel>''' for i in range(ROWS))

    gauges = "\n".join(
        f'''        <Panel id="csr_g{i}" class="CsrGauge">
          <Panel class="CsrGaugeTop">
            <Panel id="csr_g{i}_ico" class="CsrIco CsrGaugeIco" />
            <Label id="csr_g{i}_label" class="CsrGaugeLabel" text="{{s:label}}" />
            <Label id="csr_g{i}_val" class="CsrGaugeVal" text="{{s:val}}" />
          </Panel>
          <Panel class="CsrBar"><Panel id="csr_g{i}_fill" class="CsrFill" /></Panel>
        </Panel>''' for i in range(GAUGES))

    tiles = "\n".join(
        f'''            <Panel id="csr_t{i}" class="CsrTile"><Panel id="csr_t{i}_ico" class="CsrIco CsrTileIco" /></Panel>'''
        for i in range(TILES))

    return f'''<!--
  CSRoll custom HUD. GENERATED by tools/generate_hud.py - edit the generator, not this file.
  Driven by the CSRoll plugin through SwiftlyS2's CCSCustomHudLayout: per-player text variables and
  per-player class toggles. Everything starts hidden; the plugin turns parts on per player.
-->
<root>
  <styles>
    <include src="s2r://panorama/styles/custom_game/csroll_hud.vcss_c" />
  </styles>
  <Panel class="CsrScreen" hittest="false">
    <Panel id="csr_hud" class="CsrHud" hittest="false">
      <Panel id="csr_list" class="CsrList" hittest="false">
        <Label id="csr_list_title" class="CsrListTitle" text="{{s:title}}" />
{rows}
      </Panel>
      <Panel id="csr_gauges" class="CsrGauges" hittest="false">
{gauges}
      </Panel>
      <Panel id="csr_roll" class="CsrRoll" hittest="false">
        <Panel class="CsrReel">
          <Panel id="csr_strip" class="CsrStrip">
{tiles}
          </Panel>
          <Panel class="CsrMarker" />
        </Panel>
        <Panel id="csr_card" class="CsrCard">
          <Panel id="csr_card_ico" class="CsrIco CsrCardIco" />
          <Panel class="CsrCardText">
            <Label id="csr_card_cat" class="CsrCardCat" text="{{s:cat}}" />
            <Label id="csr_card_name" class="CsrCardName" text="{{s:name}}" />
            <Label id="csr_card_desc" class="CsrCardDesc" text="{{s:desc}}" />
          </Panel>
        </Panel>
      </Panel>
    </Panel>
    <Panel id="csr_prompt" class="CsrPrompt" hittest="false">
      <Label class="CsrPromptTitle" text="NEW HUD READY" />
      <Label class="CsrPromptText" text="Type !hud in chat to switch from the centre text to this HUD." />
    </Panel>
  </Panel>
</root>
'''


# ---------------------------------------------------------------------------------------------------
# Stylesheet
# ---------------------------------------------------------------------------------------------------
def fade(stops: list[tuple[float, str]]) -> str:
    """Horizontal WebKit-form gradient from a list of (position, colour)."""
    first, *middle, last = stops
    inner = ", ".join(f"color-stop( {p:.2f}, {c} )" for p, c in middle)
    inner = f", {inner}" if inner else ""
    return f"gradient( linear, 0% 0%, 100% 0%, from( {first[1]} ){inner}, to( {last[1]} ) )"


def stylesheet(icon_names: list[str]) -> str:
    out: list[str] = []
    w = out.append

    w("/* CSRoll custom HUD. GENERATED by tools/generate_hud.py - edit the generator, not this file. */")
    w("")
    w("/* Keyframes first: names quoted, brace on the same line, declared above any use. Two copies so the")
    w("   plugin can restart the spin by swapping class names - re-adding the same class sends nothing. */")
    for name in ("a", "b"):
        w(f"@keyframes 'csr-spin-{name}' {{ 0% {{ transform: translatex( 0px ); }} "
          f"100% {{ transform: translatex( -{TRAVEL}px ); }} }}")
    w("")

    w(f""".CsrScreen
{{
	width: 100%;
	height: 100%;
	overflow: noclip;
	z-index: 99999;
}}

.CsrHud
{{
	width: 100%;
	height: 100%;
	opacity: 0;
	transition-property: opacity;
	transition-duration: 0.25s;
	transition-timing-function: ease-out;
}}

.CsrHud.on
{{
	opacity: 1;
}}

/* ---------- icons: a picture class plus a category tint ---------- */
.CsrIco
{{
	background-size: contains;
	background-repeat: no-repeat;
	background-position: 50% 50%;
}}
""")
    for name in icon_names:
        w(f'.ico-{name} {{ background-image: url("s2r://panorama/images/custom_game/csroll/{name}.vsvg"); }}')
    w("")
    for cat, colour in CATEGORIES.items():
        w(f".cat-{cat} .CsrIco {{ wash-color: {colour}; }}")
    w("")

    # ---------- left list ----------
    row_shade = fade([(0, f"{SHADE}c7"), (0.55, f"{SHADE}80"), (1, f"{SHADE}00")])
    w(f""".CsrList
{{
	flow-children: down;
	width: 340px;
	horizontal-align: left;
	vertical-align: top;
	margin-left: 16px;
	margin-top: {LIST_OFFSETS[0]}px;
	visibility: collapse;
}}

.CsrList.on
{{
	visibility: visible;
}}
""")
    for i, top in enumerate(LIST_OFFSETS[1:], start=1):
        w(f".CsrList.y{i} {{ margin-top: {top}px; }}")
    w(f"""
.CsrListTitle
{{
	font-family: {FONT_BOLD};
	font-size: 15px;
	letter-spacing: 3px;
	text-transform: uppercase;
	color: #ffffffb3;
	margin-left: 4px;
	margin-bottom: 5px;
	text-shadow: 0px 1px 3px 1.0 #000000cc;
}}

.CsrRow
{{
	flow-children: right;
	width: 100%;
	padding: 6px 12px 6px 9px;
	margin-bottom: 5px;
	border-left: 4px solid #ffffff;
	background-color: {row_shade};
	visibility: collapse;
}}

.CsrRow.on
{{
	visibility: visible;
}}

.CsrRowIco
{{
	width: 34px;
	height: 34px;
	vertical-align: center;
	margin-right: 11px;
}}

.CsrRowText
{{
	flow-children: down;
	width: fill-parent-flow( 1.0 );
	vertical-align: center;
}}

.CsrRowName
{{
	width: 100%;
	font-family: {FONT_BOLD};
	font-size: 20px;
	letter-spacing: 1px;
	text-transform: uppercase;
	color: #ffffff;
	white-space: nowrap;
	text-overflow: ellipsis;
}}

.CsrRowShort
{{
	width: 100%;
	font-family: {FONT_BODY};
	font-size: 15px;
	color: #ffffffb3;
	white-space: nowrap;
	text-overflow: ellipsis;
}}
""")
    for cat, colour in CATEGORIES.items():
        w(f".CsrRow.cat-{cat} {{ border-left-color: {colour}; }}")
    w("")

    # ---------- gauges ----------
    w(f""".CsrGauges
{{
	flow-children: down;
	width: 420px;
	horizontal-align: center;
	vertical-align: bottom;
	margin-bottom: 180px;
}}

.CsrGauge
{{
	flow-children: down;
	width: 100%;
	margin-top: 14px;
	visibility: collapse;
}}

.CsrGauge.on
{{
	visibility: visible;
}}

.CsrGaugeTop
{{
	flow-children: right;
	width: 100%;
}}

.CsrGaugeIco
{{
	width: 24px;
	height: 24px;
	vertical-align: center;
	margin-right: 8px;
}}

.CsrGaugeLabel
{{
	width: fill-parent-flow( 1.0 );
	vertical-align: center;
	font-family: {FONT_BOLD};
	font-size: 17px;
	letter-spacing: 1px;
	text-transform: uppercase;
	color: #ffffffe6;
	white-space: nowrap;
	text-overflow: ellipsis;
	text-shadow: 0px 1px 4px 1.5 #000000e6;
}}

.CsrGaugeVal
{{
	vertical-align: center;
	font-family: {FONT_BOLD};
	font-size: 17px;
	color: #ffffff;
	white-space: nowrap;
	text-shadow: 0px 1px 4px 1.5 #000000e6;
}}

.CsrBar
{{
	width: 100%;
	height: 6px;
	margin-top: 5px;
	background-color: #ffffff2e;
	box-shadow: #00000099 0px 0px 5px 0px;
}}

.CsrFill
{{
	width: 100%;
	height: 100%;
	background-color: #ffffff;
	clip: rect( 0%, 0%, 100%, 0% );
	transition-property: clip;
	transition-duration: 0.12s;
	transition-timing-function: linear;
}}
""")
    for step in range(FILL_STEPS + 1):
        pct = step * 100 // FILL_STEPS
        w(f".CsrFill.f{step} {{ clip: rect( 0%, {pct}%, 100%, 0% ); }}")
    w("")
    for cat, colour in CATEGORIES.items():
        w(f".CsrGauge.cat-{cat} .CsrFill {{ background-color: {colour}; }}")
        w(f".CsrGauge.ready.cat-{cat} .CsrGaugeVal {{ color: {colour}; }}")
    w("")

    # ---------- roll ----------
    reel_shade = fade([(0, f"{SHADE}00"), (0.2, f"{SHADE}c7"), (0.8, f"{SHADE}c7"), (1, f"{SHADE}00")])
    card_shade = fade([(0, f"{SHADE}00"), (0.22, f"{SHADE}c7"), (0.78, f"{SHADE}c7"), (1, f"{SHADE}00")])
    spin = (f"animation-duration: {SPIN_SECONDS}s; "
            f"animation-timing-function: cubic-bezier( {BEZIER[0]}, {BEZIER[1]}, {BEZIER[2]}, {BEZIER[3]} ); "
            f"animation-iteration-count: 1;")
    w(f""".CsrRoll
{{
	flow-children: down;
	width: 780px;
	horizontal-align: center;
	vertical-align: top;
	margin-top: 640px;
	opacity: 0;
	transition-property: opacity;
	transition-duration: 0.35s;
	transition-timing-function: ease-out;
}}

.CsrRoll.on
{{
	opacity: 1;
}}

.CsrReel
{{
	width: {REEL_WIDTH}px;
	height: {TILE + 20}px;
	horizontal-align: center;
	overflow: clip clip;
	background-color: {reel_shade};
}}

/* The spin's end position is also the static transform, so the strip stays on the winner after
   the one-shot animation finishes. */
.CsrStrip
{{
	flow-children: right;
	width: {STRIP_WIDTH}px;
	height: {TILE}px;
	margin-left: {STRIP_LEFT}px;
	margin-top: 10px;
	transform: translatex( -{TRAVEL}px );
}}

.CsrStrip.spin-a
{{
	animation-name: 'csr-spin-a';
	{spin}
}}

.CsrStrip.spin-b
{{
	animation-name: 'csr-spin-b';
	{spin}
}}

.CsrTile
{{
	width: {TILE}px;
	height: {TILE}px;
	margin-right: {TILE_GAP}px;
	background-color: #ffffff0d;
	border-bottom: 3px solid #ffffff40;
	transition-property: transform, background-color;
	transition-duration: 0.35s;
	transition-timing-function: ease-out;
}}

.CsrTile.won
{{
	transform: scale3d( 1.12, 1.12, 1.0 );
	background-color: #ffffff26;
}}

.CsrTileIco
{{
	width: 40px;
	height: 40px;
	horizontal-align: center;
	vertical-align: center;
}}

.CsrMarker
{{
	width: 3px;
	height: 100%;
	horizontal-align: center;
	background-color: #f3c74f;
	box-shadow: #f3c74fb3 0px 0px 12px 0px;
}}

.CsrCard
{{
	flow-children: right;
	width: 100%;
	margin-top: 14px;
	padding: 14px 70px;
	background-color: {card_shade};
	opacity: 0;
	transform: translatey( 10px );
	transition-property: opacity, transform;
	transition-duration: 0.4s;
	transition-timing-function: ease-out;
}}

.CsrCard.on
{{
	opacity: 1;
	transform: translatey( 0px );
}}

.CsrCardIco
{{
	width: 84px;
	height: 84px;
	vertical-align: center;
	margin-right: 20px;
}}

.CsrCardText
{{
	flow-children: down;
	width: fill-parent-flow( 1.0 );
	vertical-align: center;
}}

.CsrCardCat
{{
	font-family: {FONT_BOLD};
	font-size: 14px;
	letter-spacing: 4px;
	text-transform: uppercase;
	color: #f3c74f;
}}

.CsrCardName
{{
	font-family: {FONT_BOLD};
	font-size: 40px;
	text-transform: uppercase;
	color: #ffffff;
	white-space: nowrap;
	text-overflow: ellipsis;
	width: 100%;
}}

.CsrCardDesc
{{
	font-family: {FONT_BODY};
	font-size: 18px;
	color: #ffffffcc;
	width: 100%;
}}
""")
    for cat, colour in CATEGORIES.items():
        w(f".CsrTile.cat-{cat} {{ border-bottom-color: {colour}; }}")
        w(f".CsrCard.cat-{cat} .CsrCardCat {{ color: {colour}; }}")
    w("")

    # ---------- prompt ----------
    prompt_shade = fade([(0, f"{SHADE}00"), (0.2, f"{SHADE}c7"), (0.8, f"{SHADE}c7"), (1, f"{SHADE}00")])
    w(f""".CsrPrompt
{{
	flow-children: down;
	width: 620px;
	horizontal-align: center;
	vertical-align: top;
	margin-top: 92px;
	padding: 10px 40px;
	background-color: {prompt_shade};
	opacity: 0;
	transition-property: opacity;
	transition-duration: 0.3s;
	transition-timing-function: ease-out;
}}

.CsrPrompt.on
{{
	opacity: 1;
}}

.CsrPromptTitle
{{
	horizontal-align: center;
	font-family: {FONT_BOLD};
	font-size: 17px;
	letter-spacing: 3px;
	color: #f3c74f;
}}

.CsrPromptText
{{
	horizontal-align: center;
	font-family: {FONT_BODY};
	font-size: 17px;
	color: #ffffffd9;
}}
""")
    return "\n".join(out)


# ---------------------------------------------------------------------------------------------------
# C# contract
# ---------------------------------------------------------------------------------------------------
def contract(icon_names: list[str]) -> str:
    icon_list = ",\n        ".join(f'"{n}"' for n in icon_names)
    cats = ", ".join(f'"{c}"' for c in CATEGORIES)
    return f'''// <auto-generated>
// GENERATED by tools/generate_hud.py - edit the generator, not this file. It writes the Panorama
// layout and stylesheet from the same spec, so every id and class below exists in the layout.
// </auto-generated>

namespace CSRoll.Hud;

public static partial class HudLayout
{{
    public const string HudPanel = "csr_hud";
    public const string PromptPanel = "csr_prompt";
    public const string ListPanel = "csr_list";
    public const string ListTitle = "csr_list_title";
    public const string RollPanel = "csr_roll";
    public const string Strip = "csr_strip";
    public const string Card = "csr_card";
    public const string CardIcon = "csr_card_ico";
    public const string CardCategory = "csr_card_cat";
    public const string CardName = "csr_card_name";
    public const string CardDescription = "csr_card_desc";

    public const int Rows = {ROWS};
    public const int Gauges = {GAUGES};
    public const int FillSteps = {FILL_STEPS};
    public const int ListOffsets = {len(LIST_OFFSETS)};

    public const int Tiles = {TILES};
    public const int StartTile = {START_TILE};
    public const int WinTile = {WIN_TILE};
    public const float SpinSeconds = {SPIN_SECONDS}f;
    public static readonly (float X1, float Y1, float X2, float Y2) SpinCurve = ({BEZIER[0]}f, {BEZIER[1]}f, {BEZIER[2]}f, {BEZIER[3]}f);

    public const string FallbackIcon = "{FALLBACK_ICON}";

    public static readonly string[] Icons =
    [
        {icon_list},
    ];

    public static readonly string[] Categories = [{cats}];

    public static string Row(int i) => $"csr_row{{i}}";
    public static string RowIcon(int i) => $"csr_row{{i}}_ico";
    public static string RowName(int i) => $"csr_row{{i}}_name";
    public static string RowShort(int i) => $"csr_row{{i}}_short";
    public static string Gauge(int i) => $"csr_g{{i}}";
    public static string GaugeIcon(int i) => $"csr_g{{i}}_ico";
    public static string GaugeLabel(int i) => $"csr_g{{i}}_label";
    public static string GaugeValue(int i) => $"csr_g{{i}}_val";
    public static string GaugeFill(int i) => $"csr_g{{i}}_fill";
    public static string Tile(int i) => $"csr_t{{i}}";
    public static string TileIcon(int i) => $"csr_t{{i}}_ico";

    public static string IconClass(string icon) => $"ico-{{icon}}";
    public static string CategoryClass(string category) => $"cat-{{category}}";
    public static string FillClass(int step) => $"f{{step}}";
    public static string ListOffsetClass(int offset) => $"y{{offset}}";

    /// <summary>Text variable names, as written in the layout's {{s:...}} slots.</summary>
    public const string VarTitle = "title";
    public const string VarName = "name";
    public const string VarShort = "short";
    public const string VarLabel = "label";
    public const string VarValue = "val";
    public const string VarCategory = "cat";
    public const string VarDescription = "desc";

    public const string On = "on";
    public const string Ready = "ready";
    public const string Won = "won";
    public const string SpinA = "spin-a";
    public const string SpinB = "spin-b";
}}
'''


def main() -> None:
    names = icons()
    LAYOUT.write_text(layout(), encoding="utf-8")
    STYLE.write_text(stylesheet(names), encoding="utf-8")
    CONTRACT.write_text(contract(names), encoding="utf-8")
    print(f"wrote {LAYOUT.relative_to(ROOT)}, {STYLE.relative_to(ROOT)}, {CONTRACT.relative_to(ROOT)} ({len(names)} icons)")


if __name__ == "__main__":
    main()
